# Generated by Django 4.1.3 on 2023-08-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BMW', max_length=40)),
                ('description', models.CharField(default='BMW good', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Audi X8', max_length=30)),
                ('dealerid', models.IntegerField(null=True)),
                ('cartype', models.CharField(choices=[('BMW', 'BMW'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('wagon', 'Wagon'), ('others', 'Others')], default='sedan', max_length=20)),
                ('year', models.DateField(null=True)),
                ('carmake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
        ),
    ]
